/** All end-user copy lives here (Thai). Short, direct, casual. */
export const TH = {
  appName: 'LINE OA Randomizer',
  nav: { results: 'ดูผลการสุ่ม', manage: 'จัดการการสุ่ม' },
  common: {
    loading: 'กำลังโหลด…',
    retry: 'ลองใหม่',
    cancel: 'ยกเลิก',
    confirm: 'ยืนยัน',
    save: 'บันทึก',
    delete: 'ลบ',
    edit: 'แก้ไข',
    back: 'กลับ',
    close: 'ปิด',
    errorTitle: 'มีบางอย่างผิดพลาด',
    baht: 'บาท',
    round: 'รอบที่',
  },
  status: { OPEN: 'ยังไม่จับ', DRAWN: 'จับแล้ว', CLOSED: 'ปิดห้อง' },
  results: {
    title: 'ผลการสุ่มของฉัน',
    empty: 'ยังไม่มีห้อง ให้เพื่อนส่งลิงก์เชิญมาให้ หรือสร้างห้องเองได้ที่แท็บจัดการ',
    redrawnBadge: 'จับใหม่',
    notDrawnYet: 'ผู้จัดยังไม่ได้จับสลาก',
    openEnvelope: 'แตะเพื่อเปิดซอง',
    youDrew: 'คุณจับได้',
    current: 'ผลปัจจุบัน',
    replaced: 'ถูกแทนที่แล้ว',
    historyTitle: 'ประวัติการจับ',
    redrawBanner: (round: number) => `ผู้จัดจับใหม่แล้ว (รอบที่ ${round}) ผลของคุณเปลี่ยนไป`,
    acknowledge: 'รับทราบ',
    saveImage: 'บันทึกเป็นรูป',
    saveImageHint: 'กดค้างที่รูปเพื่อบันทึก',
    viewAll: 'ดูผลของทุกคน',
    allResultsTitle: 'ผลของทุกคน',
    giver: 'คนจับ',
    receiver: 'ได้จับ',
  },
  manage: {
    title: 'ห้องที่ฉันจัด',
    empty: 'ยังไม่มีห้อง กดปุ่มสร้างห้องได้เลย',
    create: 'สร้างห้อง',
    newTitle: 'สร้างห้องใหม่',
    name: 'ชื่อห้อง',
    description: 'รายละเอียด (ไม่บังคับ)',
    budget: 'งบ (บาท, ไม่บังคับ)',
    exchangeDate: 'วันแลกของขวัญ (ไม่บังคับ)',
    allowViewAll: 'ให้ทุกคนดูผลของทุกคนได้',
    allowViewAllHint: 'ปิดไว้ = ทุกคนเห็นเฉพาะผลของตัวเอง',
    participants: 'ผู้เข้าร่วม',
    guest: 'ไม่มี LINE',
    organizer: 'ผู้จัด',
    invite: 'ชวนเพื่อน',
    inviteMessage: (name: string) => `มาแลกของขวัญกัน "${name}" กดลิงก์เพื่อเข้าร่วม`,
    addGuests: 'เพิ่มคนที่ไม่มี LINE',
    addGuestsHint: 'พิมพ์ชื่อ 1 ชื่อต่อ 1 บรรทัด',
    addGuestsNotice: 'ผู้จัดจะเห็นผลการจับของคนกลุ่มนี้',
    rules: 'กติกา',
    guestResults: 'ผลของคนที่ไม่มี LINE',
    draw: 'จับสลาก',
    redraw: 'จับใหม่',
    announce: 'แจ้งผลในกลุ่ม',
    announceMessage: 'จับสลากเสร็จแล้ว! เปิดเมนู "ดูผลการสุ่ม" ที่บัญชี OA ได้เลย',
    close: 'ปิดห้อง',
    closeConfirm: 'ปิดห้องจะลบผลการจับและรายชื่อทั้งหมด',
    removeConfirm: 'ลบคนนี้ออกจากห้อง?',
    notEnough: 'ต้องมีอย่างน้อย 3 คน',
  },
  feasibility: {
    OK: 'พร้อมจับสลาก',
    INFEASIBLE: 'จับสลากไม่ได้',
    TOO_FEW_PARTICIPANTS: 'คนยังไม่พอ',
  },
  rules: {
    title: 'กติกา',
    empty: 'ยังไม่มีกติกา',
    add: 'เพิ่มกติกา',
    type: 'ประเภท',
    pickPeople: 'เลือกคน',
    note: 'หมายเหตุ (ไม่บังคับ)',
    from: 'คนจับ',
    to: 'คนที่ถูกจับ',
    types: {
      MUTUAL_EXCLUDE: 'จับกันเองไม่ได้ (สองทาง)',
      ONE_WAY_EXCLUDE: 'จับได้ทางเดียว',
      GROUP_EXCLUDE: 'กลุ่มเดียวกันจับกันไม่ได้',
      HISTORY_EXCLUDE: 'ห้ามซ้ำปีก่อน',
      FORCE_ASSIGN: 'ต้องจับคนนี้',
    },
    typeHelp: {
      MUTUAL_EXCLUDE: 'เช่น คู่รัก A ↔ B',
      ONE_WAY_EXCLUDE: 'A จับ B ไม่ได้ แต่ B จับ A ได้',
      GROUP_EXCLUDE: 'เช่น คนในครอบครัวเดียวกัน',
      HISTORY_EXCLUDE: 'ปีก่อน A จับ B ไปแล้ว',
      FORCE_ASSIGN: 'A ต้องจับ B',
    },
  },
  draw: {
    title: 'จับสลาก',
    confirmDraw: 'ทุกคนจะได้ผลของตัวเอง ผลจะถูกล็อกหลังจับ',
    confirmRedraw: 'ทุกคนจะได้ผลใหม่ ผลเก่ายังเก็บไว้ให้ดูย้อนหลัง',
    drawing: 'กำลังจับสลาก…',
    done: 'จับสลากเสร็จแล้ว',
  },
  guests: {
    title: 'ผลของคนที่ไม่มี LINE',
    reveal: 'ดูผล',
    hide: 'ซ่อน',
    empty: 'ยังไม่มีคนที่เพิ่มด้วยชื่อ',
    tellThem: 'บอกผลกับแต่ละคนเอง ถ้าจับใหม่ต้องแจ้งใหม่ด้วย',
  },
  join: {
    title: 'เข้าร่วมห้อง',
    action: 'เข้าร่วม',
    already: 'คุณอยู่ในห้องนี้แล้ว',
    closed: 'ห้องนี้จับสลากไปแล้ว เข้าร่วมเพิ่มไม่ได้',
    addFriend: 'เพิ่มเพื่อนบัญชี OA เพื่อให้เมนูแสดงใน LINE',
    addFriendAction: 'เพิ่มเพื่อน',
  },
  dev: {
    badge: 'โหมดทดสอบ',
    actAs: 'ใช้งานเป็น',
    realAccount: 'บัญชี LINE จริง',
    createMock: 'สร้างผู้ใช้ทดสอบ',
    addMocks: 'เพิ่มผู้ใช้ทดสอบเข้าห้อง',
    pickIdentity: 'เลือกผู้ใช้ทดสอบเพื่อเริ่ม',
  },
} as const;
